enum Event {
    CONNECT = 'CONNECT',
    DISCONNECT = 'DISCONNECT',
    JOINCHATROOM = "JOINCHATROOM",
    MESSAGE = "MESSAGE",
    MESSAGE_COMMAND = "MESSAGE_COMMAND",
    MESSAGE_BULK = "MESSAGE_BULK",
}

export default Event
